### PR TITLE
[13.0][ADD] stock_scrap_security

### PR DESCRIPTION
**Pull request by Anxo82**
Add authorized scrap stock users

### CODE REVIEW

**Comment by dalonsod** [comment]
Looks good, I'll test it ASAP.

Meanwhile, please rename the PR in a more standard way, e.g. `[13.0][ADD] stock_scrap_security`

**Comment by dalonsod** [comment]
@ChristianSantamaria could you install it in AluTest environment?

**Comment by dalonsod** [comment]
> @ChristianSantamaria could you install it in AluTest environment?

Is this task completed?

**Comment by ChristianSantamaria** [comment]
@dalonsod Done installed in Test enviroment
@Anxo82 this addon need to add the icon

**Review by dalonsod — APPROVED** [review]
Tested :+1: 

@Anxo82 also add pending translations and squash commits

**Review by dalonsod — CHANGES_REQUESTED** [review]
Sorry, still pending another thing: models folder and its content seems to be unnecessary, since stock.scrap model definition doesn't need any changes. Could you check and remove it?

**Review by dalonsod — APPROVED** [review]
LGTM

**Pull request merged**
