### PR TITLE
[13.0][ADD] stock_picking_report_from_warehouse

### PR DESCRIPTION
**Pull request by ChristianSantamaria**
Adds from warehouse address in delivery report

imagen

### CODE REVIEW

**Comment by ChristianSantamaria** [comment]
@dalonsod can u test it in alu test enviroment?

**Comment by dalonsod** [comment]
The last change doesn't seem to be applied in AluTest environment

**Comment by ChristianSantamaria** [comment]
Srry, now it is

**Review by dalonsod — APPROVED** [review]
LGTM

**Pull request merged**
