### PR TITLE
[16.0][IMP] stock_picking_delivery_slip_a5: change font size

### PR DESCRIPTION
**Pull request by IriaAlonso**
change font size of A5 report

### CODE REVIEW

**Comment by IriaAlonso** [comment]
Before:
imagen
After:
imagen

**Comment by dalonsod** [comment]
Cool!

Anyway, I see more changes than simply reducing `font-size`, could you explain why those changes should be needed?

And, at last, for `page` class, which was original rendered font size?

**Comment by IriaAlonso** [comment]
imagen
I think there is too much space between the rows like this, what you think? @dalonsod

**Comment by IriaAlonso** [comment]
new max capacity
imagen

**Review by dalonsod — APPROVED** [review]
Tested by customer :+1: let's merge!

**Pull request merged**
